name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows manual run from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Add docker repository
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt -y update ;\
          sudo apt -y install \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg \
              lsb-release;\
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg; \
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Ubuntu dependencies
        run: |
          sudo apt -y update ;\
          sudo apt -y install \
              git \
              subversion \
              python \
              python3 \
              docker-ce \
              docker-ce-cli \
              containerd.io \
              qemu-user-static \
              binfmt-support

      - name: Pip depencencies
        run: pip install click

      - name: Build
        run: ./nightly.py build --rules=default --target=yosys

