name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows manual run from the Actions tab
  workflow_dispatch:

jobs:

  linux:
    runs-on: ubuntu-20.04

    steps:
      # Check-out under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Add docker repository
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt -y update || echo "Fix the root cause" ;\
          sudo apt -y install \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg \
              lsb-release;\
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg; \
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Ubuntu dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt -y update || echo "Fix the root cause";\
          sudo apt -y install \
              git \
              subversion \
              python \
              python3 \
              docker-ce \
              docker-ce-cli \
              containerd.io \
              qemu-user-static \
              binfmt-support

      - name: Pip depencencies
        run: pip install click

      - name: Build
        run: ./nightly.py build --rules=default --target=yosys

  mingw:
    runs-on: windows-2019

    steps:
      # Check-out under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            python3
            python3-pip

      - name: List executables
        run: C:\msys64\usr\bin\bash -lc 'ls -alh /usr/bin/'

      - name: Pip dependencies
        run: C:\msys64\usr\bin\bash -lc '/usr/bin/python3 -m pip install click'

      - name: Build
        working-directory: D:\a\fpga-nightly\fpga-nightly
        run: D:\a\fpga-nightly\fpga-nightly\nightly.bat build --rules=default --target=yosys

  choco:
    runs-on: windows-2019

    steps:
      # Check-out under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Choco dependencies
        run: choco install python msys2

      - name: Build
        run: python nightly.py build --rules=default --target=yosys

